/*
 * Class auto generated by TexturePacker
 *
 * Contains references to each image within the sprite sheet.
 *
 * https://www.codeandweb.com/texturepacker
 * $TexturePacker:SmartUpdate:9c249f83b4f96ec61c8a09e8200742d5:d881ff5ec3da86acaaa577e6ab9bd7aa:05477a09d9d5a6dca0fdadde24fc3000$
 *
 */
namespace TexturePackerSpriteDefinitions
{
	public class SpriteNames
	{
		public const string Block0 = "block0";
		public const string Block0_bounce1 = "block0_bounce1";
		public const string Block0_bounce2 = "block0_bounce2";
		public const string Block0_flash = "block0_flash";
		public const string Block0_pop = "block0_pop";
		public const string Block0_squish = "block0_squish";
		public const string Block1 = "block1";
		public const string Block1_bounce1 = "block1_bounce1";
		public const string Block1_bounce2 = "block1_bounce2";
		public const string Block1_flash = "block1_flash";
		public const string Block1_pop = "block1_pop";
		public const string Block1_squish = "block1_squish";
		public const string Block2 = "block2";
		public const string Block2_bounce1 = "block2_bounce1";
		public const string Block2_bounce2 = "block2_bounce2";
		public const string Block2_flash = "block2_flash";
		public const string Block2_pop = "block2_pop";
		public const string Block2_squish = "block2_squish";
		public const string Block3 = "block3";
		public const string Block3_bounce1 = "block3_bounce1";
		public const string Block3_bounce2 = "block3_bounce2";
		public const string Block3_flash = "block3_flash";
		public const string Block3_pop = "block3_pop";
		public const string Block3_squish = "block3_squish";
		public const string Block4 = "block4";
		public const string Block4_bounce1 = "block4_bounce1";
		public const string Block4_bounce2 = "block4_bounce2";
		public const string Block4_flash = "block4_flash";
		public const string Block4_pop = "block4_pop";
		public const string Block4_squish = "block4_squish";
		public const string SoloCursor = "soloCursor";
		public const string SoloCursor_pulse = "soloCursor_pulse";
		public const string TiledBG_default = "tiledBG_default";
		public const string TwinCursor = "twinCursor";
		public const string TwinCursor_pulse = "twinCursor_pulse";
	}
}